FoodApp/mysite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #/food/
    path('',views.IndexClassView.as_view(), name='index'),
    #/food/1
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('item/',views.item, name='item'),
    # add items
    path('add',views.CreateItem.as_view(), name='create_item'),
    # edit items
    path('update/<int:id>/',views.update_item, name='update_item'),
    # delete item
    path('delete/<int:id>/',views.delete_item, name='delete_item'),
]

FoodApp/mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    username = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://www.melbournefoodandwine.com.au/image-tools.php?w=560&h=440&src=/recipes/recipe-placeholder.jpg")
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

FoodApp/mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc','item_price','item_image']

FoodApp/mysite/food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list = Item.objects.all()

    context = {
        'item_list':item_list,
    }
    return render(request, 'food/index.html',context)


class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def item(request):
    return HttpResponse('This is an item view')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request, 'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html',{'form':form})

# This is a class based view for create item
class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)
    
    
def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

FoodApp/mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--<link rel="stylesheet" href="{% static 'food/style.css' %}"-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            <a class="nav-item nav-link" href="#">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>    
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

</body>
</html>

FoodApp/mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img  height="300px" class="card" src="{{ item.item_image }}">
        </div>

        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>{{ object.item_price }}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>




{% endblock %}

FoodApp/mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, intial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

</head>
<body>

    {% block body %}

    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="200px" width="200px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
                Added by:<h6>{{ item.user_name }}</h6>
            
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    {% endfor %}

    {% endblock %}
    
</body>
</html>

FoodApp/mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }} ?</h2>
    <button type="submit">Confirm</button>
</form>

FoodApp/mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add item
                    </div>
                </div>
                <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <button class="btn-info" type="submit">Add</button>    
                        </form>
                        
                </div>    
            </div> 
        </div>
    </div>
</div>

{% endblock %}